import type { CSSProperties } from "react";
import { getPalette, type CardTemplateId, type Palette } from "@/lib/design";
import { SafeImg } from "@/components/profile/SafeImg";
import "./card.css";

export type CardFace = {
  name: string;
  line: string;
  phone: string | null;
  email: string | null;
  photoUrl: string | null;
  qrSvg: string; // generated by src/lib/card.ts (qrcode library), never user input
  domain: string;
};

const initialsOf = (name: string) =>
  name
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase())
    .slice(0, 2)
    .join("");

// One side of a 3.5 × 2 in business card. Everything is sized in container units (cqw), so the
// same design renders identically as a thumbnail, a full-size preview, or a print sheet.
export function BusinessCard({
  design,
  palette,
  side,
  card,
  className,
}: {
  design: CardTemplateId;
  palette: Palette;
  side: "front" | "back";
  card: CardFace;
  className?: string;
}) {
  // Paper is always light, whatever the site palette.
  if (design === "paper") palette = getPalette("paper");
  const vars = {
    "--c-bg": palette.bg,
    "--c-ink": palette.ink,
    "--c-muted": palette.muted,
    "--c-accent": palette.accent,
    "--c-on-accent": palette.onAccent,
  } as CSSProperties;
  const cls = `bc bc-${design} bc-${side}${className ? ` ${className}` : ""}`;

  if (side === "back") {
    return (
      <div className={cls} style={vars} aria-label={`Back of ${card.name}'s card`}>
        <div className="bc-back">
          <div className="bc-qr" dangerouslySetInnerHTML={{ __html: card.qrSvg }} />
          <span className="bc-domain">{card.domain}</span>
        </div>
      </div>
    );
  }

  const contact = (
    <div className="bc-contact">
      {card.phone && <span>{card.phone}</span>}
      {card.email && <span>{card.email}</span>}
    </div>
  );

  return (
    <div className={cls} style={vars} aria-label={`Front of ${card.name}'s card`}>
      {design === "split" && <div className="bc-panel">{initialsOf(card.name)}</div>}
      {design === "photo" && (
        <div className="bc-avatar">
          {card.photoUrl ? (
            <SafeImg src={card.photoUrl} alt="" fallback={<span>{initialsOf(card.name)}</span>} />
          ) : (
            <span>{initialsOf(card.name)}</span>
          )}
        </div>
      )}
      <div className="bc-main">
        {design === "bold" && <div className="bc-bar" />}
        <div className="bc-id">
          <div className="bc-name">{card.name}</div>
          {card.line && <div className="bc-line">{card.line}</div>}
        </div>
        {contact}
      </div>
    </div>
  );
}
