import type { PublicProfile } from "@/lib/profile-types";

// Fictional sample person for design previews, the landing page, and card samples.
// Photos are from meetkaeden.site (with permission); everything written here is made up.
const M = "/seed/kaeden";

export const EXAMPLE: PublicProfile = {
  slug: "example",
  qrCode: "example0",
  status: "active",
  name: "John Doe",
  headline: "Computer Engineering @ State University · D2 Track & Field",
  email: "john.doe@example.com",
  phone: "555-010-0199",
  showPhoneOnSite: true,
  showPhoneOnCard: true,
  links: { github: "https://github.com", linkedin: "https://www.linkedin.com" },
  theme: { templateId: "carousel", paletteId: "gold", cardTemplateId: "classic" },
  facts: [
    { label: "Major", value: "Computer Engineering" },
    { label: "Athletics", value: "D2 Track & Field", detail: "Sprints and hurdles" },
    { label: "Academics", value: "3.8", detail: "College GPA" },
    { label: "School", value: "State University", detail: "Class of 2029" },
  ],
  resumePdfPublicUrl: null,
  noindex: true,
  slides: [
    {
      section: "About",
      title: "Hi, I'm John",
      role: "Sophomore · Computer Engineering",
      body: "I like building small things that work: apps, circuits, and the occasional robot. I run hurdles for State, teach an intro coding workshop, and work weekends at a family restaurant.",
      points: [],
      link: null,
      tint: "#6b5a2a",
      media: { type: "image", url: `${M}/about.jpg`, fit: "contain" },
    },
    {
      section: "Education",
      title: "B.S. Computer Engineering",
      role: "State University · 2025 – Present",
      body: null,
      points: ["GPA 3.8, Dean's List both semesters", "Coursework: Digital Logic, Data Structures, Circuits I"],
      link: null,
      tint: "#2a2f45",
      media: null,
    },
    {
      section: "Projects",
      title: "Campus Ride Board",
      role: "Personal project · 2026",
      body: null,
      points: [
        "Web app where students post and join rides home for breaks; about 300 users in the first month",
        "Built with React and a small Node API; sign-in with school email",
      ],
      link: null,
      tint: "#1f3d5c",
      media: null,
    },
    {
      section: "Projects",
      title: "Plant Watering Sensor",
      role: "Intro to Engineering · 2025",
      body: null,
      points: [
        "Soil-moisture sensor and pump on a microcontroller that waters a plant when the soil dries out",
        "Wrote the firmware and designed the 3D-printed case",
      ],
      link: null,
      tint: "#2d4a3a",
      media: null,
    },
    {
      section: "Leadership",
      title: "Coding Workshop Instructor",
      role: "Community College Summer Program · 2026",
      body: null,
      points: ["Taught weekly beginner Python sessions to a class of 20", "Helped students debug their first projects one on one"],
      link: null,
      tint: "#2d4a3a",
      media: { type: "image", url: `${M}/circuitpython.jpg`, position: "center 40%" },
    },
    {
      section: "Leadership",
      title: "Student Council",
      role: "Class Representative · 2024 – 2025",
      body: null,
      points: ["Planned the spring service day with 150 volunteers", "Ran the class budget and fundraising"],
      link: null,
      tint: "#5c4a1f",
      media: { type: "image", url: `${M}/leadership.jpg`, position: "center 52%" },
    },
    {
      section: "Athletics",
      title: "Track & Field",
      role: "State University · NCAA Division II",
      body: null,
      points: ["Sprints and 110m hurdles", "Team Academic Honor Roll"],
      link: null,
      tint: "#2a2f45",
      media: { type: "image", url: `${M}/track.jpg`, position: "center 15%" },
    },
    {
      section: "Work",
      title: "Line Cook & Trainer",
      role: "Family restaurant · 2023 – Present",
      body: null,
      points: ["Prep and line work through weekend rushes", "Train new hires on prep, the register, and food safety"],
      link: null,
      tint: "#5c2a1f",
      media: { type: "image", url: `${M}/gosan.jpg`, position: "center 35%" },
    },
    {
      section: "Skills",
      title: "Skills",
      role: "Tools I use",
      body: null,
      points: ["Python, JavaScript, C", "React, Node, Git", "Arduino, soldering, 3D printing"],
      link: null,
      tint: "#1f2f3a",
      media: null,
    },
    {
      section: "Awards",
      title: "Awards",
      role: "2024 – 2026",
      body: null,
      points: ["Dean's List (2)", "Conference Academic Honor Roll", "Food Handler Certificate"],
      link: null,
      tint: "#6b5a2a",
      media: { type: "image", url: `${M}/awards.jpg`, position: "center 20%" },
    },
  ],
  future: [{ title: "Senior design", body: "A low-cost sensor kit for school science classes." }],
};
