import type { PublicProfile } from "@/lib/profile-types";

// Mirrors the live meetkaeden.site (reference/portfolio/index.html). Used to seed the database,
// and as the /kaeden fallback when no DATABASE_URL is configured (local dev, preview builds).
// In points, **text** renders bold.
const M = "/seed/kaeden";

export const KAEDEN: PublicProfile = {
  slug: "kaeden",
  qrCode: "kaedenw8",
  status: "active",
  name: "Kaeden Wellman",
  headline: "Electrical Engineering @ UCCS · D2 Track & Field · Builder",
  email: "kaeden.wellman@gmail.com",
  phone: "480-696-9274",
  showPhoneOnSite: true,
  showPhoneOnCard: true,
  links: {
    github: "https://github.com/kaedenwellman",
    linkedin: "https://www.linkedin.com/in/kaeden-wellman-a45237377",
  },
  theme: { templateId: "carousel", paletteId: "gold", cardTemplateId: "classic" },
  facts: [
    { label: "Major", value: "B.S. Electrical Engineering" },
    { label: "Athletics", value: "UCCS Division II Track & Field", detail: "400m / 110m hurdles" },
    { label: "Academics", value: "4.0 UW / 4.36 W", detail: "High school GPA, Magna Cum Laude" },
    { label: "School", value: "University of Colorado Colorado Springs", detail: "Fall 2026 – Present" },
  ],
  resumePdfPublicUrl: `${M}/resume.pdf`,
  noindex: false,
  slides: [
    {
      section: "About",
      title: "Hi, I'm Kaeden",
      role: "College freshman · Chandler, AZ → Colorado Springs",
      body: "I'm a college freshman. I build software and embedded projects, teach what I build, and have been elected to leadership in every volunteer organization I've stayed with for over a year.",
      points: [],
      link: null,
      tint: "#6b5a2a",
      media: { type: "image", url: `${M}/about.jpg`, fit: "contain" },
    },
    {
      section: "Education",
      title: "B.S. Electrical Engineering",
      role: "University of Colorado Colorado Springs · Fall 2026 – Present",
      body: null,
      points: [
        "UCCS Division II Track & Field (400m / 110m hurdles)",
        "Arizona College Prep High School, Chandler, AZ: Graduated May 2026, Magna Cum Laude",
        "4.0 UW / 4.36 W · College-level Physics and Calculus",
      ],
      link: null,
      tint: "#2a2f45",
      media: { type: "image", url: `${M}/track.jpg`, position: "center 15%" },
    },
    {
      section: "Projects",
      title: "Halle Reviews",
      role: "Solo full-stack build · Diane & Bruce Halle Foundation, 2026",
      body: null,
      points: [
        "AI-assisted grant review application that replaces the foundation reviewers' improvised Zoom + NotebookLM + ChatGPT workflow; each grant moves through an LOI → Application → Funded → Completed lifecycle with LLM summarization at every stage, driven by editable Markdown rubrics.",
        "Sole developer, ~6,200 lines of TypeScript/JavaScript in three weeks: Vite + React 18 + TypeScript + Tailwind on Vercel, Node + Express on Railway, push-to-main continuous deployment.",
        "Multi-provider LLM layer (Anthropic, OpenAI, Google) behind a single streaming SSE interface with a server-side persisted key store; real Microsoft Entra ID sign-in (MSAL + jose JWT validation) and per-user workspace persistence.",
      ],
      link: null,
      tint: "#2d4a3a",
      media: { type: "image", url: `${M}/halle-reviews.webp` },
    },
    {
      section: "Projects",
      title: "Lightsaber Duel Game",
      role: "Microchip DevDay Hackathon winner · Best Project Award, 2026",
      body: null,
      points: [
        "Built a physical lightsaber dueling game linking a Microchip Curiosity board (CircuitPython, IMU, NeoPixels, LCD, audio) to a browser game via the Web Serial API.",
        "Streamed motion data as JSON over USB serial at 10 Hz; shipped three deployable modes (classic side-by-side, first-person, combined).",
        "Only non-intern in a field of college interns; debugged the full stack solo using Claude to understand root causes, not just fixes.",
      ],
      link: { label: "github.com/kaedenwellman/lightsaber", href: "https://github.com/kaedenwellman/lightsaber" },
      tint: "#1f3d5c",
      media: { type: "video", url: `${M}/lightsaber.mp4`, position: "center 30%" },
    },
    {
      section: "Projects",
      title: "Other Projects",
      role: "Gyftloop · Teen Startup Kits · Link Crew Website · HOA Website",
      body: null,
      points: [
        "**Gyftloop** (co-founder, with wellmanaz): live product that tracks birthdays and anniversaries, then emails three tailored gift ideas one week before each occasion. Vanilla JS on Vercel Edge Functions, Neon Postgres, Auth0, and OpenAI embeddings for reranking.",
        "**Teen Startup Kits** (founder, Arizona LLC, 2026): Shopify business selling service-business starter kits for teens 13–18. Filed the LLC and designed the three-tier pricing and a creator affiliate model; first kit live.",
        "**Link Crew Website** (Arizona College Prep): interactive site replacing a static PowerPoint for the Link Crew program, with a gated section for selected leaders. Built and deployed on GitHub Pages.",
        "**HOA Website**: web build for a local Homeowners Association.",
      ],
      link: { label: "gyftloop.com", href: "https://gyftloop.com" },
      tint: "#5c2a1f",
      media: { type: "image", url: `${M}/gyftloop.webp`, position: "center 30%" },
    },
    {
      section: "Teaching & leadership",
      title: "CircuitPython Instructor",
      role: "Microchip DevDay, Pima Community College · July 2026",
      body: null,
      points: [
        "Invited by the DevDay program's creator to co-lead the class after winning the hackathon; first student-to-instructor transition in the program's history.",
        "Taught embedded CircuitPython to a class of about 25 college students, most with no prior coding experience.",
        "Guided students through progressive hands-on projects on the Microchip PyKit Explorer board; ran one-on-one debugging sessions with students who got stuck.",
      ],
      link: null,
      tint: "#2d4a3a",
      media: { type: "image", url: `${M}/circuitpython.jpg`, position: "center 40%" },
    },
    {
      section: "Teaching & leadership",
      title: "Other Leadership",
      role: "Mountain Lion Strong · Best Buddies · Link Crew · Hurdle coaching · Athletic Leadership Council",
      body: null,
      points: [
        "**Member, Mountain Lion Strong** (UCCS, Fall 2026 – Present): NCAA grant-funded mental wellness and resilience program for UCCS student-athletes, focused on identity, healthy relationships, goal setting, and holistic wellness.",
        "**Event Coordinator, Arizona Best Buddies Friendship Walk** (2025–2026): coordinated logistics for the statewide walk and drove a measurable increase in underclassman participation from my school; chapter officer supporting Friendship Ball, Hot Cocoa Run, Trunk-or-Treat, and fundraising.",
        "**Commissioner, Link Crew** (Arizona College Prep, 2025–2026): senior leadership role covering event planning, supply coordination, donor outreach, and multi-school coordination.",
        "**Volunteer Hurdle Coach** (2+ years): coach youth and middle school hurdlers, extending the mentorship model of the coach who worked with me.",
        "**Athletic Leadership Council Officer** (Arizona College Prep).",
      ],
      link: null,
      tint: "#5c4a1f",
      media: { type: "image", url: `${M}/leadership.jpg`, position: "center 52%" },
    },
    {
      section: "Work",
      title: "Assistant Chef & Staff Trainer",
      role: "Gosan Poke and Roll (family-owned restaurant) · March 2024 – Present",
      body: null,
      points: [
        "Multi-role at a family-owned small business: kitchen operations, staff training, and social media content.",
        "Trained new employees on prep, POS, and service standards; ran a high-volume kitchen through peak service.",
        "Hands-on exposure to the operational realities of running a small business: inventory, labor, and customer experience.",
      ],
      link: null,
      tint: "#5c2a1f",
      media: { type: "image", url: `${M}/gosan.jpg`, position: "center 35%" },
    },
    {
      section: "Skills",
      title: "Technical Skills",
      role: "What I build with",
      body: null,
      points: [
        "Languages: Python, JavaScript, HTML/CSS",
        "AI & APIs: Claude API, OpenAI API, prompt engineering, streaming SSE, Web Serial API",
        "Web: React, Vite, Tailwind, Node, Express, Vercel, Railway",
        "Auth & Data: Microsoft Entra ID (MSAL, JWT), Auth0 (PKCE), Neon Postgres",
        "Embedded: CircuitPython, Microchip PyKit Explorer, Microchip Curiosity board, IMU/NeoPixel/LCD peripherals",
        "Tools: GitHub, VS Code, Shopify, Google Apps Script",
      ],
      link: null,
      tint: "#1f3d5c",
      media: null,
    },
    {
      section: "Awards",
      title: "Certifications & Awards",
      role: "Recognition",
      body: null,
      points: [
        "Anthropic AI Fluency · Anthropic Claude 101 (Claude Corps prerequisites, completed)",
        "2026 Superintendent's Outstanding Citizenship Award",
        "Best Project Award, Microchip DevDay Hackathon (2026)",
        "2025 Track & Field MVP · 2024 AZ Track & Field All-Academic Team · 2023 Freshman MVP",
        "CTE Software and Design Knight Award",
        "Food Managers Certification · Food Handlers Permit",
      ],
      link: null,
      tint: "#6b5a2a",
      media: { type: "image", url: `${M}/awards.jpg`, position: "center 20%" },
    },
  ],
  future: [
    {
      title: "Realtor Hub",
      body: "A single dashboard for a real estate agent: listings, a client tracker, and AI agents that draft emails and social posts.",
    },
    { title: "KW Digital Office", body: "A multi-agent AI layer that runs across school, training, and business." },
    {
      title: "Project Jarvis",
      body: "A custom AI system with six specialized agents that handle research, writing, scheduling, strategy, compliance, and management across every area of my life, all tied together by a manager agent who compiles a daily briefing. The end goal is a physical wall-mounted device with a wake word, speaker, and pico projector that serves as the voice and face of the whole system, turning it into a real-life Jarvis from Iron Man.",
    },
  ],
};
